"""add specifications column to products

Revision ID: 01984e5915f5
Revises: 8bc17c08e447
Create Date: 2026-04-08 14:21:18.941457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01984e5915f5'
down_revision = '8bc17c08e447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specifications', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('specifications')

    # ### end Alembic commands ###
