"""restore_customer_atomic_fields

Revision ID: 036150c66af6
Revises: fef36dffc606
Create Date: 2026-03-30 14:20:04.395116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '036150c66af6'
down_revision = 'fef36dffc606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=75), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('last_name', sa.String(length=75), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('requires_freight', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('exterior_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('interior_number', sa.String(length=20), nullable=True))
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)

    # Migrate existing data: split full_name into first_name/last_name
    op.execute("""
        UPDATE customers
        SET first_name = SUBSTRING_INDEX(full_name, ' ', 1),
            last_name = TRIM(SUBSTR(full_name, LENGTH(SUBSTRING_INDEX(full_name, ' ', 1)) + 2))
        WHERE full_name IS NOT NULL AND full_name != ''
    """)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_column('received_quantity')

    with op.batch_alter_table('furniture_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('address', mysql.TEXT(), nullable=True))
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('interior_number')
        batch_op.drop_column('exterior_number')
        batch_op.drop_column('street')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('requires_freight')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
