"""remove_address

Revision ID: 1f18de3129b9
Revises: 23bda7251005
Create Date: 2026-03-28 21:57:07.112390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f18de3129b9'
down_revision = '23bda7251005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
