"""add_payments_table

Revision ID: 21616489b4f1
Revises: 036150c66af6
Create Date: 2026-03-30 14:29:28.333277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21616489b4f1'
down_revision = '036150c66af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id_payment', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('SALE', 'ORDER', name='payment_type_enum'), nullable=False),
    sa.Column('id_sale', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_sale'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id_payment')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
