"""customer_update

Revision ID: 23bda7251005
Revises: 65d5850bef03
Create Date: 2026-03-28 21:51:40.221277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23bda7251005'
down_revision = '65d5850bef03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=75), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=75), nullable=False))
        batch_op.add_column(sa.Column('requires_freight', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('exterior_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('interior_number', sa.String(length=20), nullable=True))
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', mysql.VARCHAR(length=150), nullable=False))
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('interior_number')
        batch_op.drop_column('exterior_number')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('street')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('requires_freight')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
