"""RF-VENT-01: add id_customer, id_employee, active to sales

Revision ID: 2f4af87837d2
Revises: e363036a0950
Create Date: 2026-03-25 19:13:43.720942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f4af87837d2'
down_revision = 'e363036a0950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('id_customer', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_employee', sa.Integer(), nullable=False))
        batch_op.alter_column('payment_method_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['id_employee'], ['id'])
        batch_op.create_foreign_key(None, 'customers', ['id_customer'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('payment_method_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('id_employee')
        batch_op.drop_column('id_customer')
        batch_op.drop_column('active')

    # ### end Alembic commands ###
