"""update product_image model with columns for cloudinary

Revision ID: 4fb1f037c349
Revises: c4f2a8b7d901
Create Date: 2026-04-03 11:51:09.318603

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4fb1f037c349"
down_revision = "c4f2a8b7d901"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("orders_ibfk_5"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("orders_ibfk_4"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("orders_ibfk_3"), type_="foreignkey")
        batch_op.drop_column("deactivated_at")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("updated_by")
        batch_op.drop_column("created_at")
        batch_op.drop_column("created_by")
        batch_op.drop_column("deactivated_by")

    with op.batch_alter_table("product_images", schema=None) as batch_op:
        batch_op.alter_column(
            "image_url", existing_type=mysql.VARCHAR(length=500), nullable=True
        )
        batch_op.alter_column(
            "public_id", existing_type=mysql.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "sort_order", existing_type=mysql.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product_images", schema=None) as batch_op:
        batch_op.alter_column(
            "sort_order", existing_type=mysql.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "public_id", existing_type=mysql.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "image_url", existing_type=mysql.VARCHAR(length=500), nullable=False
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "deactivated_by", mysql.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("created_by", mysql.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "created_at",
                mysql.DATETIME(),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("updated_by", mysql.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                mysql.DATETIME(),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("deactivated_at", mysql.DATETIME(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("orders_ibfk_3"), "users", ["deactivated_by"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("orders_ibfk_4"), "users", ["created_by"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("orders_ibfk_5"), "users", ["updated_by"], ["id"]
        )

    # ### end Alembic commands ###
