"""Add description column to colors table

Revision ID: 505375a5a3f9
Revises: 4f8c2a9e3b1d
Create Date: 2026-03-19 00:00:12.601983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505375a5a3f9'
down_revision = '4f8c2a9e3b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colors', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
