"""add table wood_types

Revision ID: 6067bf0c7322
Revises: e57af1e0a8f8
Create Date: 2026-02-18 01:13:08.227832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6067bf0c7322'
down_revision = 'e57af1e0a8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wood_types',
    sa.Column('id_wood_type', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_wood_type'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wood_types')
    # ### end Alembic commands ###
