"""Added Payment model

Revision ID: 65d5850bef03
Revises: 2f4af87837d2
Create Date: 2026-03-26 01:21:12.217312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d5850bef03'
down_revision = '2f4af87837d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payments',
    sa.Column('id_payment', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('SALE', 'ORDER', name='payment_type_enum'), nullable=False),
    sa.Column('id_sale', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_sale'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id_payment')
    )
    with op.batch_alter_table('raw_material_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=False))

    with op.batch_alter_table('raw_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_id'], ['id'])
        batch_op.create_foreign_key(None, 'material_categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_materials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('status')
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('category_id')
        batch_op.drop_column('description')

    with op.batch_alter_table('raw_material_movements', schema=None) as batch_op:
        batch_op.drop_column('reason')

    op.drop_table('payments')
    op.drop_table('material_categories')
    # ### end Alembic commands ###
