"""add material_categories relation to raw_materials

Revision ID: 81483d6d4264
Revises: 70b134232c8f
Create Date: 2026-03-21 20:35:22.447005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81483d6d4264'
down_revision = '70b134232c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'material_categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_materials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
