"""add fields to payment methods

Revision ID: 86938400748c
Revises: 8b98bc0a9380
Create Date: 2026-03-20 01:56:50.728336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86938400748c'
down_revision = '8b98bc0a9380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('available_pos', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('available_ecommerce', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('abbreviation'))
        batch_op.drop_index(batch_op.f('name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('abbreviation'), ['abbreviation'], unique=True)

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('available_ecommerce')
        batch_op.drop_column('available_pos')
        batch_op.drop_column('status')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
