"""RawMaterials_v2

Revision ID: 96af9c9fa783
Revises: 01f875dd8f12
Create Date: 2026-03-29 16:48:01.059677

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "96af9c9fa783"
down_revision = "01f875dd8f12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raw_materials", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=False,
            )
        )
        batch_op.create_foreign_key(
            None, "material_categories", ["category_id"], ["id"]
        )
        batch_op.drop_column("supplier_id")
        batch_op.drop_column("estimated_cost")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raw_materials", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "estimated_cost", mysql.DECIMAL(precision=12, scale=2), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "supplier_id", mysql.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
