"""add timestamps to purchase_order

Revision ID: ccf2ff3e189f
Revises: e363036a0950
Create Date: 2026-03-23 19:29:51.771343

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ccf2ff3e189f"
down_revision = "e363036a0950"
branch_labels = None
depends_on = None


def upgrade():
    # Avoid errors when the columns already exist (e.g., merge + parallel branches).
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_columns = {
        column["name"] for column in inspector.get_columns("purchase_orders")
    }

    if "created_at" not in existing_columns or "updated_at" not in existing_columns:
        with op.batch_alter_table("purchase_orders", schema=None) as batch_op:
            if "created_at" not in existing_columns:
                batch_op.add_column(
                    sa.Column(
                        "created_at",
                        sa.DateTime(),
                        server_default=sa.text("CURRENT_TIMESTAMP"),
                        nullable=False,
                    )
                )
            if "updated_at" not in existing_columns:
                batch_op.add_column(
                    sa.Column(
                        "updated_at",
                        sa.DateTime(),
                        server_default=sa.text("CURRENT_TIMESTAMP"),
                        nullable=False,
                    )
                )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("purchase_orders", schema=None) as batch_op:
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
