"""add minimum_stock to raw_materials

Revision ID: cd5b2b0fdde9
Revises: 7c4b1e2d9a10
Create Date: 2026-04-05 15:20:12.044293

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "cd5b2b0fdde9"
down_revision = "7c4b1e2d9a10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raw_materials", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "minimum_stock", sa.Numeric(precision=12, scale=3), nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raw_materials", schema=None) as batch_op:
        batch_op.drop_column("minimum_stock")

    # ### end Alembic commands ###
