"""Update supplier model with timestamps and unique constraints

Revision ID: e363036a0950
Revises: 86938400748c
Create Date: 2026-03-22 03:04:46.026239

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e363036a0950"
down_revision = "86938400748c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=False,
            )
        )
        batch_op.create_unique_constraint(None, ["name"])
        batch_op.create_unique_constraint(None, ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
