"""create roles table

Revision ID: e57af1e0a8f8
Revises: 5aa5020316c5
Create Date: 2026-02-17 18:08:02.238330

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e57af1e0a8f8'
down_revision = '5aa5020316c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('id_role', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('created_by', sa.String(length=100), nullable=True),
                    sa.Column('updated_by', sa.String(length=100), nullable=True),
                    sa.Column('deleted_by', sa.String(length=100), nullable=True),
                    sa.PrimaryKeyConstraint('id_role'),
                    sa.UniqueConstraint('name')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
