"""Add subtitle, image_url and slug to furniture_types

Revision ID: edc745f354f5
Revises: 2f4af87837d2
Create Date: 2026-03-28 23:17:15.081728

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "edc745f354f5"
down_revision = "2f4af87837d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("furniture_types", schema=None) as batch_op:
        batch_op.add_column(sa.Column("subtitle", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column("image_url", sa.String(length=500), nullable=True)
        )
        batch_op.add_column(sa.Column("slug", sa.String(length=120), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_furniture_types_slug"), ["slug"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("furniture_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_furniture_types_slug"))
        batch_op.drop_column("slug")
        batch_op.drop_column("image_url")
        batch_op.drop_column("subtitle")

    # ### end Alembic commands ###
