"""add received_quantity to purchase_order_items

Revision ID: fb32db85d5be
Revises: ccf2ff3e189f
Create Date: 2026-03-28 23:26:20.434001

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "fb32db85d5be"
down_revision = "ccf2ff3e189f"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_columns = {
        column["name"] for column in inspector.get_columns("purchase_order_items")
    }

    if "received_quantity" not in existing_columns:
        with op.batch_alter_table("purchase_order_items", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "received_quantity",
                    sa.Numeric(precision=12, scale=3),
                    nullable=False,
                )
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("purchase_order_items", schema=None) as batch_op:
        batch_op.drop_column("received_quantity")

    # ### end Alembic commands ###
